# Generated by Django 5.0.1 on 2024-01-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='productos.categoria'),
        ),
    ]
