# Generated by Django 5.0.1 on 2024-01-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_productos_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
