# Generated by Django 5.0.1 on 2024-01-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('productos', '0003_categoria_is_selected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AlterField(
            model_name='productos',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='categorias.categoria'),
        ),
    ]
