# Generated by Django 5.0.1 on 2024-01-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('productos', '0004_delete_categoria_alter_productos_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categorias',
            field=models.ManyToManyField(blank=True, limit_choices_to={'nombre__ne': 'Todos'}, to='categorias.categoria'),
        ),
    ]
